version: "3.3"
services:
  passwordapi:
    image: felopez/passwordapi:0.0.1
  balancer:
    image: nginx:1.23.0-alpine
    ports:
      - 8999:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - passwordapi
